### ISSUE TITLE
automatic release of tagged versions

### ISSUE THREAD

**Issue by hunchback** [IBM/the-mesh-for-data#120] opened 2020-11-05 08:43 UTC
Releasing the-mesh-for-data enables defining a stable reference point, it also enables to track when essential APIs are changed or persistent format has changed.

To reduce overhead the release method would be by git tagging which the goal of this issue to perform all needed operations automatically to create the github release.

As is standard we use tags which follow Semantic Versioning Specification (SemVer), so using versions of form vX.Y.Z (e.g. v0.0.1).

On the tagging of a branch and then merging to master we would like to trigger the creation of a release including at minimum the tag.gz of the source tree, later including also a CHANGELOG and later uploading all the binary products of the release (docker images, helm charts, etc).

Out of scope at first stage is considering anything which is beyond the main repo (the-mesh-for-data), going forward we need to rethink the module/connector structure so as not to have to duplicate efforts done in the core repo to auxiliary repos.

**Comment by roee88** [comment] 2020-11-10 07:52
Duplicate of #82?

**Closed** 2020-11-15 14:58 UTC
